# Generated by Django 4.2 on 2026-04-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_organization_remove_projectuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('project_engineer', 'Project Engineer'), ('data_contributor', 'Data Contributor')], default='project_engineer', max_length=50),
            preserve_default=False,
        ),
    ]
