# Generated by Django 4.2 on 2026-04-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='role',
        ),
    ]
