# Generated by Django 4.2 on 2026-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
