# Generated by Django 5.2.10 on 2026-05-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimdata',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointclouddata',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='original_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
