# Generated by Django 6.0.6 on 2026-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_add_transform_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
