# Generated by Django 6.0.6 on 2026-06-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
        ("projects", "0015_project_footprint_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bim_date", models.DateField(blank=True, null=True)),
                ("pointcloud_date", models.DateField(blank=True, null=True)),
                ("total_elements", models.IntegerField(default=0)),
                ("completed_elements", models.IntegerField(default=0)),
                ("in_progress_elements", models.IntegerField(default=0)),
                ("not_started_elements", models.IntegerField(default=0)),
                ("overall_completion", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.bimdata",
                    ),
                ),
                (
                    "pointcloud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.pointclouddata",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element_id", models.CharField(max_length=120)),
                ("element_type", models.CharField(max_length=80)),
                ("category", models.CharField(blank=True, max_length=40)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("bim_area", models.FloatField(default=0.0)),
                ("overlap_area", models.FloatField(default=0.0)),
                ("completion", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="processing.progressassessment",
                    ),
                ),
            ],
        ),
    ]
