# Generated by Django 6.0.6 on 2026-06-13 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0002_progressassessment_progresselement"),
        ("projects", "0015_project_footprint_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlignmentPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("kabsch", "Kabsch (point pairs)"),
                            ("icp", "ICP refine"),
                            ("manual", "Manual / saved"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("fitness", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("relative_transform", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.bimdata",
                    ),
                ),
                (
                    "pointcloud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.pointclouddata",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignment_pairs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("bim", "pointcloud")},
            },
        ),
    ]
