# Generated by Django 6.0.6 on 2026-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_alignmentpair"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentpair",
            name="bim_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alignmentpair",
            name="pointcloud_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
