# Generated by Django 6.0.5 on 2026-08-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_alignmentpair_bim_date_alignmentpair_pointcloud_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresselement',
            name='bim_area',
        ),
        migrations.RemoveField(
            model_name='progresselement',
            name='overlap_area',
        ),
        migrations.AddField(
            model_name='progresselement',
            name='bim_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresselement',
            name='bim_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='progresselement',
            name='overlap_points',
            field=models.IntegerField(default=0),
        ),
    ]
