# Generated by Django 6.0.5 on 2026-08-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_remove_progresselement_bim_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentpair',
            name='bim_element_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alignmentpair',
            name='overlap_element_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alignmentpair',
            name='overlap_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alignmentpair',
            name='overlap_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
