# Generated by Django 6.0.5 on 2026-09-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_alignmentpair_bim_element_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressassessment',
            name='alignment_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='processing.alignmentpair'),
        ),
    ]
