export const buttonStyles = {
  base: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    marginBottom: "10px",
    transition: "0.2s ease",
  },

  primary: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    marginBottom: "10px",
    backgroundColor: "#3b82f6",
    color: "white",
  },

  orange: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    marginBottom: "10px",
    backgroundColor: "#f97316",
    color: "white",
  },

  gray: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    marginBottom: "10px",
    backgroundColor: "#6b7280",
    color: "white",
  },

  success: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    marginBottom: "10px",
    backgroundColor: "#10b981",
    color: "white",
  },

  danger: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    marginBottom: "10px",
    backgroundColor: "#ef4444",
    color: "white",
  },
};
