# Generated by Django 4.2 on 2026-04-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('project_manager', 'Project Manager'), ('project_engineer', 'Project Engineer'), ('data_contributor', 'Data Contributor')], max_length=30, null=True),
        ),
    ]
