# Generated by Django 4.2 on 2026-04-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sub_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sub_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('member', 'Member'), ('project_manager', 'Project Manager'), ('project_engineer', 'Project Engineer'), ('data_contributor', 'Data Contributor')], max_length=30),
        ),
    ]
