# Generated by Django 4.2 on 2026-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_sub_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
