# Generated by Django 6.0.6 on 2026-06-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
